name: startick
description: "A Ticket Management System Project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  built_value: ^8.3.3 # for handling json serialization and creating immutable objects
  built_collection: ^5.1.1
  cool_dropdown: ^2.1.0
  cupertino_icons: ^1.0.6
  carousel_slider: ^5.0.0
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  dropdown_button2: ^2.3.9
  qr_code_scanner: ^1.0.1
  http: ^1.2.2
  email_validator: ^2.1.17
  fluttertoast: ^8.2.12
  flutter_screenutil: ^5.9.0
  http_interceptor: ^2.0.0
  pinput: ^5.0.1
  provider: ^6.0.3
  permission_handler: ^11.3.1
  mobile_scanner: ^6.0.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  statusbarz: ^1.0.14
  tuple: ^2.0.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  built_value_generator: ^8.3.3
  flutter_lints: ^3.0.0

dependency_overrides:
  win32: ^5.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Archivo
      fonts:
        - asset: fonts/Archivo-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700